# Generated by Django 5.2.16 on 2026-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
