# Generated by Django 5.2.16 on 2026-07-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='infants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='legs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Round Trip', 'Round Trip'), ('Multi-City', 'Multi-City')], default='One Way', max_length=20),
        ),
    ]
