# Generated by Django 5.2.16 on 2026-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_adults_booking_children_booking_infants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_manifest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
