# Generated by Django 5.2.16 on 2026-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_addons_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fare_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
