# Generated by Django 4.2.13 on 2026-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_addons_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancellation Requested', 'Cancellation Requested'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('In Flight', 'In Flight')], default='Confirmed', max_length=50),
        ),
    ]
