# Generated by Django 4.2.13 on 2026-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_update_booking_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
