# Generated by Django 5.2.16 on 2026-07-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_fare_type_booking_gst_number'),
        ('bookings', '0005_add_cancellation_data'),
    ]

    operations = [
    ]
