# Generated by Django 4.2.13 on 2026-08-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_merge_20260731_2137'),
        ('bookings', '0006_merge_20260731_2219'),
    ]

    operations = [
    ]
