# Generated by Django 5.2.16 on 2026-07-31 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_upgrade_otpverification_secure'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('aadhaar', 'Aadhaar Card'), ('visa', 'Visa Document'), ('medical', 'Medical Clearance')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Verified', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_kyc_documents',
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
