# Generated by Django 4.2.13 on 2026-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_alter_boat_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='boat',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='boat',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
