# Generated by Django 5.2.16 on 2026-07-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Goa', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tag',
            field=models.CharField(default='GOISAFE LUXURY', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(default='4.8/5.0', max_length=10),
        ),
    ]
